app/models.py
import sqlalchemy
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), unique=True, nullable=False)
    

app/__init__.py
# app/__init__.py
from flask import Flask
from .hello.routes import hello_bp # Importa o blueprint que criamos
from .models import db


def create_app():
    # Cria a instância da aplicação Flask
    app = Flask(__name__)
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///hello.db'
    db.init_app(app)

    with app.app_context():
        db.create_all()

    # Registra o blueprint na aplicação
    app.register_blueprint(hello_bp)
    # Retorna a aplicação configurada
    return app

app/hello/routes.py
# app/hello/routes.py
from flask import Blueprint, render_template, request, redirect, url_for
from ..models import User, db
# Cria um objeto Blueprint. 'hello' é o nome do blueprint.
hello_bp = Blueprint('hello', __name__)
# Define uma rota dentro deste blueprint.
@hello_bp.route('/')
def index():
    usuarios = User.query.all() #['André', 'Rafael', 'Fernando']
    return render_template ('index.html', usuarios = usuarios)

@hello_bp.route('/novousuario', methods=['POST'])
def novoUsuario():
    nome_usuario = request.form['nome_usuario']

    novo_usuario= User(username = nome_usuario)

    db.session.add(novo_usuario)
    db.session.commit()
    return redirect('/')

@hello_bp.route('/removerUsuario/<int:usuario_id>', methods=['POST'])
def removerUsuario(usuario_id):
    usuario = User.query.get(usuario_id)
    if usuario:
        db.session.delete(usuario)
        db.session.commit()
    return redirect(url_for('hello.index'))

@hello_bp.route('/editarUsuario/<int:usuario_id>', methods=["POST"])
def editarUsuario(usuario_id):
    usuario =User.query.get(usuario_id)
    if usuario:
        usuario.username = request.form['nome_usuario']
        db.session.commit()
    return redirect(url_for('hello.index'))

app/templates/index.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hello World</title>
</head>
<body>
<h1> Criar Usuário</h1>
<form  action='/novousuario' method="POST">
    <label for="name"> Nome Usuário</label>
    <input type="text" id="name" name="nome_usuario" required>
    <button type="submit"> Cadastrar Usuário</button>
</form>

<h1> Usuarios</h1>
<ul>
    {% for usuario in usuarios %}
    <li>
        <form action="{{url_for('hello.editarUsuario', usuario_id=usuario.id)}}",
        method="POST">
            <input type='text' name="nome_usuario" value="{{usuario.username}}" required> 
            <button type="submit"> Atualizar </button>
        </form>


        <form action="{{url_for('hello.removerUsuario', usuario_id=usuario.id)}}",
        method="POST">
        <button action="submit"> Remover</button>
    </form>
    </li>
    {% endfor %}
</ul>
</body>
</html>